import { IntelligenceItem } from "@/lib/types";
import { getWeekId } from "@/lib/dates";
import { uid } from "@/lib/utils";
function item(input: Omit<IntelligenceItem, "id" | "weekId" | "relevanceScore">): IntelligenceItem {
  return { ...input, id: uid(input.title + input.url), weekId: getWeekId(input.publishedAt.slice(0, 10)), relevanceScore: 50 };
}
export const seedItems: IntelligenceItem[] = [
  item({ title: "HBO Max revela teaser oficial da nova serie Harry Potter", source: "HBO / Wizarding World", sourceKind: "official", url: "https://www.harrypotter.com/news/watch-the-first-teaser-for-hbo-original-harry-potter-series-premiering-christmas-2026", publishedAt: "2026-03-25T12:00:00.000Z", summary: "Marco inicial do monitoramento: teaser oficial, titulo da primeira temporada e janela de estreia no Natal de 2026.", sentiment: "positive", sentimentReason: "Evento oficial de alto impacto.", riskScore: 18, opportunityScore: 96, tags: ["teaser", "official", "hbo", "launch"], reach: 96, region: "Global" }),
  item({ title: "Fandom brasileiro reage ao primeiro teaser e ao retorno a Hogwarts", source: "Google News Brasil", sourceKind: "news", url: "https://news.google.com/search?q=Harry%20Potter%20HBO%20Max%20Brasil", publishedAt: "2026-03-28T15:00:00.000Z", summary: "Conversas no Brasil se concentram em nostalgia, fidelidade aos livros e comparacoes com os filmes.", sentiment: "positive", sentimentReason: "Reacao inicial favoravel.", riskScore: 24, opportunityScore: 86, tags: ["brasil", "fandom", "nostalgia"], reach: 78, region: "BR" }),
  item({ title: "Discussoes sobre elenco e tom da adaptacao ganham tracao", source: "Reddit", sourceKind: "reddit", url: "https://www.reddit.com/search/?q=Harry%20Potter%20HBO%20series", publishedAt: "2026-04-07T11:20:00.000Z", summary: "Comunidades debatem expectativas, casting, ritmo da historia e diferencas em relacao aos filmes.", sentiment: "neutral", sentimentReason: "Debate misto.", riskScore: 52, opportunityScore: 62, tags: ["casting", "reddit", "adaptation"], reach: 62, region: "Global" }),
  item({ title: "Buscas por Harry Potter HBO Max sobem apos teaser", source: "Google Trends Brasil", sourceKind: "trends", url: "https://trends.google.com/trends/explore?geo=BR&q=Harry%20Potter%20HBO%20Max", publishedAt: "2026-04-15T10:00:00.000Z", summary: "Interesse de busca indica oportunidade de calendario editorial e captura de demanda organica.", sentiment: "positive", sentimentReason: "Sinal de intencao ativa.", riskScore: 14, opportunityScore: 91, tags: ["trends", "search", "brasil"], reach: 88, region: "BR" }),
  item({ title: "Videos brasileiros explicam tudo sobre a nova serie", source: "YouTube Brasil", sourceKind: "youtube", url: "https://www.youtube.com/results?search_query=Harry+Potter+HBO+Max+serie+Brasil", publishedAt: "2026-05-03T18:00:00.000Z", summary: "Creators e canais geek produzem videos de contexto, teorias e comparativos com a saga original.", sentiment: "positive", sentimentReason: "Formato recomendado para educacao e aquecimento de fandom.", riskScore: 20, opportunityScore: 88, tags: ["youtube", "creators", "contexto"], reach: 82, region: "BR", creator: "Canais geek BR" }),
  item({ title: "Parte do fandom critica escolhas e teme perda de magia original", source: "Social Listening", sourceKind: "x", url: "https://x.com/search?q=Harry%20Potter%20HBO%20Max", publishedAt: "2026-05-18T21:00:00.000Z", summary: "Sinais negativos aparecem em conversas sobre comparacao com os filmes e possiveis mudancas criativas.", sentiment: "negative", sentimentReason: "Risco reputacional em comparacao direta com os filmes.", riskScore: 72, opportunityScore: 51, tags: ["risk", "fandom", "comparison"], reach: 67, region: "BR" }),
  item({ title: "Portais geek retomam cobertura com listas de elenco e easter eggs", source: "Omelete / IGN Brasil", sourceKind: "news", url: "https://www.omelete.com.br/harry-potter", publishedAt: "2026-06-08T13:00:00.000Z", summary: "Cobertura editorial favorece formatos de listas, retrospectivas, easter eggs e guias para novos espectadores.", sentiment: "positive", sentimentReason: "Oportunidade editorial sustentada.", riskScore: 18, opportunityScore: 84, tags: ["press", "easter-eggs", "editorial"], reach: 74, region: "BR" }),
  item({ title: "Buzz estabiliza e pede reforco de narrativa ate o proximo asset oficial", source: "Lumos Analysis", sourceKind: "google", url: "https://annakarolinesilveiradelima-dotcom.github.io/lumos/", publishedAt: "2026-07-10T16:00:00.000Z", summary: "Sem novo asset massivo, a conversa depende de memoria nostalgica, creators e recirculacao de informacoes oficiais.", sentiment: "neutral", sentimentReason: "Sinal de manutencao, nao de pico.", riskScore: 32, opportunityScore: 70, tags: ["always-on", "strategy", "weekly"], reach: 55, region: "BR" })
];
