export type Sentiment = "positive" | "neutral" | "negative";
export type SourceKind = "news" | "google" | "trends" | "youtube" | "reddit" | "x" | "creator" | "official";
export type IntelligenceItem = {
  id: string;
  title: string;
  source: string;
  sourceKind: SourceKind;
  url: string;
  publishedAt: string;
  weekId: string;
  summary: string;
  sentiment: Sentiment;
  sentimentReason: string;
  riskScore: number;
  opportunityScore: number;
  relevanceScore: number;
  tags: string[];
  reach: number;
  region: string;
  creator?: string;
};
export type WeeklySnapshot = {
  weekId: string;
  weekLabel: string;
  startDate: string;
  endDate: string;
  totalItems: number;
  positive: number;
  neutral: number;
  negative: number;
  buzzScore: number;
  riskScore: number;
  opportunityScore: number;
  topTopics: string[];
  keyNarrative: string;
  whatChanged: string;
  executiveReadout: string[];
  items: IntelligenceItem[];
};
export type TimelineEvent = {
  date: string;
  weekId: string;
  title: string;
  description: string;
  intensity: number;
  sentiment: Sentiment;
  items: string[];
};
export type IntelligenceSnapshot = {
  project: string;
  generatedAt: string;
  dateFrom: string;
  dateTo: string;
  totalItems: number;
  currentWeekId: string;
  weeks: WeeklySnapshot[];
  items: IntelligenceItem[];
  timeline: TimelineEvent[];
  summary: {
    headline: string;
    bullets: string[];
    risks: string[];
    opportunities: string[];
    sentiment: { positive: number; neutral: number; negative: number };
    topSources: { source: string; count: number }[];
  };
  trends: { date: string; value: number; topic: string }[];
  creators: { name: string; platform: string; score: number; audience: string; fit: string; risks: string[] }[];
};
